[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING = "1"
  NEXT_PUBLIC_STATIC_EXPORT = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/"
  status = 301

[[redirects]]
  from = "/portfolio"
  to = "/portfolio/"
  status = 301

[[redirects]]
  from = "/analytics"
  to = "/analytics/"
  status = 301

[[redirects]]
  from = "/settings"
  to = "/settings/"
  status = 301

[[redirects]]
  from = "/bridge"
  to = "/bridge/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
