name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      - name: Run unit/integration tests
        run: pnpm test

      - name: Start dev server for E2E tests
        run: pnpm dev &
        env:
          CI: true

      - name: Wait for dev server
        run: |
          sleep 15
          curl -f http://localhost:3000 || exit 1

      - name: Run E2E tests
        run: pnpm playwright:test
        env:
          CI: true

      - name: Generate coverage report
        run: pnpm coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info

      - name: Build app
        run: pnpm build
        env:
          NEXT_PUBLIC_STATIC_EXPORT: true

      - name: Verify build output
        run: |
          ls -la out/
          echo "Build verification complete"

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Set Sentry release
        run: echo "SENTRY_RELEASE=$(pnpm exec sentry-cli releases propose-version)" >> $GITHUB_ENV

      - name: Upload source maps to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ env.SENTRY_RELEASE }}
        run: pnpm exec sentry-cli sourcemaps upload --org igorms --project neodash --release $SENTRY_RELEASE .next

      # - name: Deploy (optional)
      #   run: echo "Add your deployment step here"
